import type { Config } from 'tailwindcss'

export default <Partial<Config>>{
  theme: {
    extend: {
      colors: {
        "tertiary-dim": "#714600",
        "on-primary-fixed-variant": "#0e009d",
        "on-surface": "#272e42",
        "surface-container-low": "#eef0ff",
        "on-secondary-fixed": "#6f001e",
        "primary-container": "#9396ff",
        "tertiary-fixed-dim": "#e79400",
        "on-secondary": "#ffefef",
        "on-error-container": "#510017",
        "surface": "#f6f6ff",
        "primary-fixed": "#9396ff",
        "surface-tint": "#4647d3",
        "error-dim": "#a70138",
        "surface-container-high": "#d9e2ff",
        "on-error": "#ffefef",
        "secondary-dim": "#a20030",
        "primary-fixed-dim": "#8387ff",
        "on-secondary-container": "#93002a",
        "secondary": "#b80438",
        "on-tertiary-fixed-variant": "#563400",
        "on-primary-fixed": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#0a0081",
        "secondary-fixed": "#ffc2c5",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#060e20",
        "on-tertiary": "#fff0e3",
        "error": "#b41340",
        "surface-container": "#e2e7ff",
        "inverse-on-surface": "#959cb5",
        "inverse-primary": "#8083ff",
        "surface-dim": "#c7d4fa",
        "error-container": "#f74b6d",
        "secondary-container": "#ffc2c5",
        "primary-dim": "#3939c7",
        "surface-bright": "#f6f6ff",
        "outline": "#6f768e",
        "tertiary": "#815100",
        "on-tertiary-container": "#4a2c00",
        "tertiary-container": "#f8a010",
        "on-secondary-fixed-variant": "#a40030",
        "outline-variant": "#a5adc6",
        "on-background": "#272e42",
        "primary": "#4647d3",
        "tertiary-fixed": "#f8a010",
        "secondary-fixed-dim": "#ffaeb3",
        "background": "#f6f6ff",
        "surface-container-highest": "#d1dcff",
        "surface-variant": "#d1dcff",
        "on-surface-variant": "#535b71",
        "on-primary": "#f4f1ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
      },
    },
  },
}
